name: Artificial
favicon: null
layout_spectrum: 0.36626
typography_spectrum: 0.8263369107153267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000606'
    - '#91788d'
    - '#d75943'
    - '#6f2f3f'
    - '#233d3a'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.4785344486590475
purpose: []
