name: Artificial
favicon: null
layout_spectrum: 0.04178
typography_spectrum: 0.8263369107153267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#dad9d5'
    - '#1a1915'
    - '#b5b1ae'
    - '#55504c'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
