name: Artificial
favicon: null
layout_spectrum: 0.50589
typography_spectrum: 0.8263369107153267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9863d'
    - '#1d1626'
    - '#bf303c'
    - '#604c38'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.4785344486590475
purpose: []
