name: Artificial
favicon: null
layout_spectrum: 0.35990927484817803
typography_spectrum: 0.8263369107153267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5272613905835897
  lightness: 0.7097936167847365
  saturation: 0.1961616009939462
  rhythmicContrast: 0.4785344486590475
purpose: []
